version: '3.9'

volumes:
  mongodb-sepomex:

services:
  web-sepomex:
    build: .
    container_name: web-sepomex
    image: custom/web-sepomex:v1
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: ${API_ENVIROMENT}
      MONGO_USERNAME: ${CUSTOM_MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${CUSTOM_MONGO_ROOT_PASSWORD}
  mongo:
    image: "mongo:${MONGO_TAG}"
    container_name: mongo-sepomex
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CUSTOM_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CUSTOM_MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-sepomex:/data/db
