version: '3.9'

volumes:
  mongodb-sepomex:

services:
  api-sepomex:
    build: .
    container_name: api-sepomex
    image: custom/api-sepomex:v1
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: ${API_ENVIROMENT}
  mongo:
    image: "mongo:${MONGO_TAG}"
    volumes:
      - mongodb-sepomex:/data/db
