name: CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to docker
        uses: docker/build-push-action@v2
        with:
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          push: true
          tags: ${{ github.sha  }}

